services:

  postgres:
    image: postgres:17
    container_name: animal-hotel-db
    environment:
      POSTGRES_DB: animal_hotel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - animal-hotel-network

  animal-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: animal-hotel-app
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - animal-hotel-network

  report-service:
    build:
      context: ./report-service
      dockerfile: Dockerfile
    container_name: animal-hotel-report
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - animal-hotel-network

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: animal-hotel-gateway
    depends_on:
      - animal-service
      - report-service
    ports:
      - "8080:8080"
    networks:
      - animal-hotel-network

networks:
  animal-hotel-network:

volumes:
  postgres_data: