services:
  postgres:
    image: postgres:17
    container_name: animal-hotel-db
    environment:
      POSTGRES_DB: animal_hotel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - animal-hotel-network

  app:
    build: .
    container_name: animal-hotel-app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - animal-hotel-network

networks:
  animal-hotel-network:

volumes:
  postgres_data: